backend: python

ThorlabsLTS150:
  alias: lts150
  x:  
    serial: 45140764
    lower_limit: 0
    upper_limit: .14
  y:
    serial: 45141924
    lower_limit: 0
    upper_limit: .29
  z:
    serial: 45146974

